# -*- coding: utf-8 -*-
"""datamining-aditya-eko-nugroho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tVKv1K36Jpr4di-2_ldZdxTt1IDMPp3E
"""

import pandas as pd

dataset = pd.read_csv("Benign Traffic.csv")

dataset

dataset2 = pd.read_csv("DDoS ICMP Flood.csv")

dataset

dataset3 = pd.read_csv("DDoS UDP Flood.csv")

dataset

hasilgabung =pd.concat([dataset,dataset2,dataset3],ignore_index=True)

hasilgabung.columns.values

x = hasilgabung.iloc[:,7: 76]

x

y = hasilgabung.iloc[:,83: 84]

y

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 42)

from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

adit = DecisionTreeClassifier(criterion='entropy', splitter = 'random')
adit.fit(x_train, y_train)

y_pred = adit.predict(x_test)

y_pred

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

accuracy

import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize = (10, 7))
tree.plot_tree(adit, feature_names = x.columns.values, class_names = np.array([ 'Benign Traffic','DDos ICMP Flood','DDoS UDP Flood']), filled = True)
plt.show()

import seaborn as lol
from sklearn import metrics
label = np.array([ 'Benign Traffic', 'DDos ICMP Flood', 'DDoS UDP Flood'])

import matplotlib.pyplot as plt
conf_matrix = metrics.confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 10))
lol.heatmap(conf_matrix, annot=True, xticklabels=label, yticklabels=label)
plt.xlabel('Prediksi')
plt.ylabel('Fakta')
plt.show()